# Generated by Django 5.0 on 2024-05-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "eleccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatos",
                        to="api.eleccion",
                    ),
                ),
            ],
        ),
    ]
