# Generated by Django 5.0 on 2024-05-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_candidatos"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuariosRegistrados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("codigoSis", models.IntegerField(unique=True)),
                ("foto", models.ImageField(upload_to="fotos/")),
                ("huella_dactilar", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Voto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_usuario", models.IntegerField(unique=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "id_candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.candidatos"
                    ),
                ),
            ],
        ),
    ]
