# Generated by Django 5.0.7 on 2024-11-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_facultades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='api.facultades')),
            ],
        ),
    ]
