# Generated by Django 5.0.7 on 2024-11-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Rol',
        ),
    ]
