# Generated by Django 5.0.7 on 2024-11-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='api.eleccion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jurado', to='api.user')),
            ],
        ),
    ]
