# Generated by Django 5.0.7 on 2024-12-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elecciones', to='api.carreras'),
        ),
    ]
